### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by vanagpau** [marl-book/codebase#32]
Hi I'm trying to run the first few lines of code in the book and encountering an issue running the first environment/algorithm:

I'm running a fresh install of Ubuntu and have followed all the installation instructions
```
Error executing job with overrides: ['+algorithm=ia2c', 'env.name=lbforaging:Foraging-8x8-2p-3f-v3', 'env.time_limit=25']
Traceback (most recent call last):
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'utils' has no attribute 'envs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myname/codebase/marlbase/utils/envs.py", line 7, in <module>
    from marlbase.utils import wrappers as mwrappers
ModuleNotFoundError: No module named 'marlbase'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'utils.envs.make_env':
ModuleNotFoundError("No module named 'marlbase'")
Are you sure that 'envs' is importable from module 'utils'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/myname/codebase/marlbase/run.py", line 51, in <module>
    main()
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/myname/codebase/marlbase/run.py", line 18, in main
    env = hydra.utils.call(cfg.env, seed=cfg.seed)
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/myname/miniconda3/envs/marlbase/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'utils.envs.make_env', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: env
```

**Comment by vanagpau** [comment]
working now, I think I had missed the '.' on the ```pip install -e .``` command
